device: auto    # auto / cpu / cuda

output_dir: "runs"
run_name: "train_clean_val_clean_test_noisy" 

test_mode: "noisy"               # clean / noisy / denoised

# clean data
clean_dir: "C:\\temp\\KWS\\data\\speech-commands-v2"
folder_start: 0
folder_end: 6

# background noises
bg_noise_dir: "C:\\temp\\KWS\\data\\speech-commands-v2\\_background_noise_"

# noise parameters
noise_ops: ["pink_noise", "doing_the_dishes", "white_noise", "running_tap", "exercise_bike", "dude_miaowing", "all"]
snr_choices: [-20, -10, 0, 10, 20]
random_noise_start: true          # random crop location inside noise file
noise_if_short: "loop"            # loop / repeat / pad_zeros
noisy_test_seed: 123              # for reproducibility

sampling_rate: 16000

n_mfcc: 13
use_parallel: true

train_ratio: 0.8
val_ratio: 0.1
test_ratio: 0.1
random_state: 42

batch_size: 64
num_workers: 0
shuffle_train: true

epochs: 150
patience: 10
lr: 0.001
weight_decay: 0.001

train_basic: false
train_improved: true

make_confusion: true
show_plots: true

mis_enabled: true
mis_random_pair: true
mis_seed: 123
mis_max_rows: 50

# confusion matrix controls
cm_single: true       
cm_compare: true       