device: auto    # auto / cpu / cuda

output_dir: "runs"

data_sources:
  clean_dir: "C:\\temp\\KWS\\data\\speech-commands-v2"
  noisy_dir: "C:\\temp\\KWS\\data\\generated_noisy"
  # denoised_dir: 

folders:
  clean:    [0, 6]
  noisy:    [0, 6]
  # denoised: [0, 6]

sampling_rate: 16000

n_mfcc: 13
use_parallel: true

train_ratio: 0.8
val_ratio: 0.1
test_ratio: 0.1
random_state: 42

batch_size: 64
num_workers: 0
shuffle_train: true

epochs: 150
patience: 10
lr: 0.001
weight_decay: 0.001

train_basic: false
train_improved: true

make_confusion: true
show_plots: true

mis_enabled: true
mis_true_label: "bed"
mis_pred_label: "bird"
mis_max_rows: 50

val_source: clean               # clean / noisy / denoised
test_sources: [clean, noisy]    # clean / noisy / denoised

run_name: "trainClean_valClean" # trainClean_valClean / trainClean_valNoisy
