# config.yaml
device: auto    # auto / cpu / cuda

output_dir: "/home/dsi/skopavi/Project/kws_project/outputs/runs"

train_mode: "clean"                
val_mode: "clean"                  
test_mode: ["clean", "noisy", "denoised", "enhanced_sgmse", "enhanced_trained_ep10", "enhanced_trained_ep20", "all"]   

# clean data
clean_dir: "/home/dsi/skopavi/Project/kws_project/data/raw/data_new"
folder_start: 0
folder_end: 5

# background noises
bg_noise_dir: "/home/dsi/skopavi/Project/kws_project/data/raw/data_new/_background_noise_"

# noise parameters
noise_ops: ["pink_noise", "doing_the_dishes", "white_noise", "running_tap", "exercise_bike", "dude_miaowing", "all"]
snr_choices: [ -10, 0, 10]
random_noise_start: true          # random crop location inside noise file
noise_if_short: "loop"            # loop / repeat / pad_zeros
noisy_test_seed: 123              # for reproducibility

sampling_rate: 16000

n_mfcc: 13
use_parallel: true

train_ratio: 0.8
val_ratio: 0.1
test_ratio: 0.1
random_state: 42

batch_size: 64
num_workers: 0
shuffle_train: true

epochs: 150
patience: 10
lr: 0.001
weight_decay: 0.001


show_plots: true
# MIS controls
mis_enabled: true
mis_random_pair: true
mis_seed: 123
mis_max_rows: 100

# confusion matrix controls
make_confusion: true
cm_single: true       
cm_compare: true       

use_unet_denoiser: false  # true / false