# new_config.yaml

device: auto    # auto / cpu / cuda

output_dir: "/home/dsi/skopavi/Project/kws_project/outputs/new_runs"
clean_dir: "/home/dsi/skopavi/Project/kws_project/data/raw/data_new"
meta: "/home/dsi/skopavi/Project/kws_project/data/noisy_new_metadata.csv"
noisy_dir: "/home/dsi/skopavi/Project/kws_project/data/noisy_new"
enh_baseline: "/home/dsi/skopavi/Project/kws_project/data/enhanced_new/baseline"
enh_trained: "/home/dsi/skopavi/Project/kws_project/data/enhanced_new/trained_ep166"
enh_new_dir : "/home/dsi/skopavi/Project/kws_project/data/enhanced_new"

folder_start: 19
folder_end: 25

sampling_rate: 16000
n_mfcc: 13

batch_size: 64
num_workers: 0

epochs: 100
patience: 10
lr: 0.001
weight_decay: 0.0001

shuffle_train: true
use_parallel: true
random_state: 42